### ISSUE TITLE
OpenCL Support

### ISSUE THREAD

**Issue by ryanvade** [kipr/meta-kipr#53]
According to the TI website, the TI AM3354 has support for OpenCL 1.1.10 but the build doesn't appear to have the libraries installed.  Are they in a different location or not installed at all?

As a side note, the TI AM3354 is supported by kernel 4.4 which has better support for the wifi interface. I'm curious why the 3.18 kernel is being used instead.

**Comment by jsoutherland** [comment]
OpenCL isn't installed at all (the recipes don't exist in our build).  No one had expressed an interest yet.  I think we would either have to update meta-ti or add via http://arago-project.org/git/?p=meta-arago.git;a=blob;f=meta-arago-extras/recipes-ti/ocl/opencl_git.bb;hb=master

It takes a lot of work to get things patched and stable for a given board and kernel version (https://github.com/kipr/meta-kipr/pull/8/files) and there is some motivation to stick with what Gumstix is using so that we can collaborate more easily.  I have not heard of any issues with WiFi.  What is improved?  Most of these things come down to time and priorities with me being the only developer on staff.

**Comment by ryanvade** [comment]
Apologies for my late reply. 

I definitely have an interest in OpenCL support.   I was looking into it and found that in order to update meta-ti  openembeded would also have to be updated.  I didn't go any further down the dependency trail but I'm not sure that is a good idea.  Perhaps the other approach would be better?

As for wireless improvements, in general kernel 4.0 had overall wifi stack improvements across almost every chip.  TI has specifically been working with 4.4 to support their products.  I mostly just asked out of curiosity.  I understand the time required to work on a stable kernel.

**Comment by jsoutherland** [comment]
Sorry I haven't had a chance to try either bitbake approach yet.

I haven't done much with OpenCL... I worked directly with CUDA in the past.   Maybe it is possible to compile your OpenCL programs on the Wallaby (instead of cross-compiling via bitbake) for now?   

(edit:  I mean compile the programs and OpenCL on the Wallaby)

**Comment by ryanvade** [comment]
Not sure.  I wanted to experiment with the libwallaby functions on OpenCL.
